// <auto-generated />
using System;
using AnalistaPalmaseg.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnalistaPalmaseg.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827213535_AddPastasProdutor")]
    partial class AddPastasProdutor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RelatorioRenovacaoId")
                        .HasColumnType("integer");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioRenovacaoId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Apolice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataFimVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicioVigencia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimentoPagamento")
                        .HasColumnType("date");

                    b.Property<int>("ImportacaoApoliceId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroApolice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("Premio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ramo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segurado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Seguradora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoApoliceId");

                    b.ToTable("Apolices");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClienteDesde")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email1")
                        .HasColumnType("text");

                    b.Property<string>("Email2")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text");

                    b.Property<string>("Historico")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroEndereco")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Prefixo1")
                        .HasColumnType("text");

                    b.Property<string>("Prefixo2")
                        .HasColumnType("text");

                    b.Property<string>("Prefixo3")
                        .HasColumnType("text");

                    b.Property<string>("Profissao")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("Telefone1")
                        .HasColumnType("text");

                    b.Property<string>("Telefone2")
                        .HasColumnType("text");

                    b.Property<string>("Telefone3")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" != ''");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.DistribuicaoReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<decimal>("ComissaoRef")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PremioLiquidoRef")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QtdApolicesRef")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DistribuicaoReferencias");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.FuncionarioResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Comissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ImportacaoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Meta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PercentualComissao")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Premio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Seguradora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("FuncionariosResultados");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Importacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("ArquivoOrigem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<string>("Produtor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Produtor", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("Importacoes");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.ImportacaoApolice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoOrigem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ImportadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("ImportacoesApolice");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Fechou")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechouEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Indicacao")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("Produtor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segurado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SeguroGerado")
                        .HasColumnType("boolean");

                    b.Property<int?>("SeguroNovoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.MetaCrescimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhEquipe")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PercentualMeta")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorBonus")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MetasCrescimento");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.MetaPremiacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhTodas")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int?>("QuantidadeMinima")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorBonus")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MetasPremiacao");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.MetaSeguradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MetaPremio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeguradoraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeguradoraId", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("MetasSeguradoras");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.NovoNegocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Comissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmitidoPor")
                        .HasColumnType("text");

                    b.Property<decimal>("Fator")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("ImportacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("Pl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segurado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Vigencia")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("NovosNegocios");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.PastaProdutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Caminho")
                        .IsUnique();

                    b.ToTable("PastasProdutor");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.RelatorioRenovacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AcidentesPassageiroFranquia")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AcidentesPassageiroLmi")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AcidentesPassageiroPremio")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Agencia")
                        .HasColumnType("text");

                    b.Property<int?>("AnoFabricacao")
                        .HasColumnType("integer");

                    b.Property<int?>("AnoModelo")
                        .HasColumnType("integer");

                    b.Property<string>("Apolice")
                        .HasColumnType("text");

                    b.Property<string>("ArquivoOrigem")
                        .HasColumnType("text");

                    b.Property<bool>("AssinaturaFeita")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Banco")
                        .HasColumnType("text");

                    b.Property<int>("BoletosGerados")
                        .HasColumnType("integer");

                    b.Property<string>("Bonus")
                        .HasColumnType("text");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("CepPernoite")
                        .HasColumnType("text");

                    b.Property<string>("Chassi")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClienteDesde")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CodigoDocumento")
                        .HasColumnType("text");

                    b.Property<string>("CodigoFipe")
                        .HasColumnType("text");

                    b.Property<string>("Combustivel")
                        .HasColumnType("text");

                    b.Property<decimal>("Comissao")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ComissaoAdicional")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ComissaoGerada")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Conta")
                        .HasColumnType("text");

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<decimal>("DanosCorporaisFranquia")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DanosCorporaisLmi")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DanosCorporaisPremio")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DanosMaterialFranquia")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DanosMaterialLmi")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DanosMateriasPremio")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DanosMoraisFranquia")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DanosMoraisLmi")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DanosMoraisPremio")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("DataControle")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DescricaoItem")
                        .HasColumnType("text");

                    b.Property<string>("DocumentoPrincipal")
                        .HasColumnType("text");

                    b.Property<string>("Email1")
                        .HasColumnType("text");

                    b.Property<string>("Email2")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Emissao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmitidoPor")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Endosso")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text");

                    b.Property<string>("Fabricante")
                        .HasColumnType("text");

                    b.Property<string>("Falecido")
                        .HasColumnType("text");

                    b.Property<string>("FechamentoAssinatura")
                        .HasColumnType("text");

                    b.Property<decimal?>("FechamentoComissao")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("FechamentoFormaPagamento")
                        .HasColumnType("text");

                    b.Property<string>("FechamentoParcelamento")
                        .HasColumnType("text");

                    b.Property<decimal?>("FechamentoPremioLiquido")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("FechamentoSeguradora")
                        .HasColumnType("text");

                    b.Property<string>("Financiado")
                        .HasColumnType("text");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text");

                    b.Property<decimal>("FranquiaApolice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("ImportadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Iof")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("LiquidoFatura")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<string>("MotivoSituacao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Nascimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NegocioCorretora")
                        .HasColumnType("text");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text");

                    b.Property<string>("NovoProdutor")
                        .HasColumnType("text");

                    b.Property<string>("NumeroEndereco")
                        .HasColumnType("text");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<string>("ObservacaoDocumento")
                        .HasColumnType("text");

                    b.Property<string>("Pasta")
                        .HasColumnType("text");

                    b.Property<string>("PedidoEndosso")
                        .HasColumnType("text");

                    b.Property<decimal?>("PercentualComissaoMinimo")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Placa")
                        .HasColumnType("text");

                    b.Property<string>("Prefixo1")
                        .HasColumnType("text");

                    b.Property<string>("Prefixo2")
                        .HasColumnType("text");

                    b.Property<string>("Prefixo3")
                        .HasColumnType("text");

                    b.Property<decimal>("PremioAdicional")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PremioCusto")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PremioLiquido")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PremioTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Produto")
                        .HasColumnType("text");

                    b.Property<string>("Profissao")
                        .HasColumnType("text");

                    b.Property<string>("Proposta")
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeEndossos")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeSinistros")
                        .HasColumnType("integer");

                    b.Property<string>("Ramo")
                        .HasColumnType("text");

                    b.Property<string>("Renavam")
                        .HasColumnType("text");

                    b.Property<string>("Seguradora")
                        .HasColumnType("text");

                    b.Property<string>("SeguradoraAnterior")
                        .HasColumnType("text");

                    b.Property<bool>("SeguroEmitido")
                        .HasColumnType("boolean");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<string>("SituacaoAcompanhamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StatusItem")
                        .HasColumnType("text");

                    b.Property<string>("Telefone1")
                        .HasColumnType("text");

                    b.Property<string>("Telefone2")
                        .HasColumnType("text");

                    b.Property<string>("Telefone3")
                        .HasColumnType("text");

                    b.Property<string>("TipoRecebimento")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalFatura")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("Transmissao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("ValorDeterminado")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorParcelas")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VendedorPrincipal")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VigenciaFinal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("VigenciaInicial")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ZeroKm")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Proposta")
                        .IsUnique()
                        .HasFilter("\"Proposta\" IS NOT NULL");

                    b.ToTable("RelatorioRenovacoes");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Renovacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CiaRenovada")
                        .HasColumnType("text");

                    b.Property<decimal>("Comissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmitidoPor")
                        .HasColumnType("text");

                    b.Property<decimal>("Fator")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("ImportacaoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("NovaComissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NovoPl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<decimal>("PlBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ramo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SaldoPl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Segurado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Vigencia")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("Renovacoes");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.ResultadoMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Funcionario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImportacaoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Meta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Realizado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImportacaoId");

                    b.ToTable("Resultados");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Seguradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsParceira")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Seguradoras");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.SeguroNovo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AssinaturaFeita")
                        .HasColumnType("boolean");

                    b.Property<int>("BoletosGerados")
                        .HasColumnType("integer");

                    b.Property<string>("Cia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<string>("EmitidoPor")
                        .HasColumnType("text");

                    b.Property<decimal?>("Fator")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Financeiro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Parcelas")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Pl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Segmento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segurado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SeguroEmitido")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Vigencia")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("SeguroNovos");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoAcesso")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.ValorReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Colaborador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ComissaoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("PremioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Colaborador", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("ValoresReferencia");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Apolice", b =>
                {
                    b.HasOne("AnalistaPalmaseg.Core.Models.ImportacaoApolice", null)
                        .WithMany("Apolices")
                        .HasForeignKey("ImportacaoApoliceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.FuncionarioResultado", b =>
                {
                    b.HasOne("AnalistaPalmaseg.Core.Models.Importacao", null)
                        .WithMany("FuncionariosResultados")
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.MetaSeguradora", b =>
                {
                    b.HasOne("AnalistaPalmaseg.Core.Models.Seguradora", "Seguradora")
                        .WithMany()
                        .HasForeignKey("SeguradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguradora");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.NovoNegocio", b =>
                {
                    b.HasOne("AnalistaPalmaseg.Core.Models.Importacao", "Importacao")
                        .WithMany("NovosNegocios")
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importacao");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.PastaProdutor", b =>
                {
                    b.HasOne("AnalistaPalmaseg.Core.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Renovacao", b =>
                {
                    b.HasOne("AnalistaPalmaseg.Core.Models.Importacao", "Importacao")
                        .WithMany("Renovacoes")
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importacao");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.ResultadoMeta", b =>
                {
                    b.HasOne("AnalistaPalmaseg.Core.Models.Importacao", null)
                        .WithMany("Resultados")
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.Importacao", b =>
                {
                    b.Navigation("FuncionariosResultados");

                    b.Navigation("NovosNegocios");

                    b.Navigation("Renovacoes");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("AnalistaPalmaseg.Core.Models.ImportacaoApolice", b =>
                {
                    b.Navigation("Apolices");
                });
#pragma warning restore 612, 618
        }
    }
}
